// This file was generated by Mendix Modeler 7.18.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the MyFirstModule module
	public static java.util.Date cALCULATE_DUE_DATE(IContext context, myfirstmodule.proxies.Tab _tab)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Tab", _tab == null ? null : _tab.getMendixObject());
			return (java.util.Date)Core.execute(context, "MyFirstModule.CALCULATE_DUE_DATE", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void cHANGE_OWNER(IContext context, myfirstmodule.proxies.Product _product, myfirstmodule.proxies.Tab _tab)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			params.put("Tab", _tab == null ? null : _tab.getMendixObject());
			Core.execute(context, "MyFirstModule.CHANGE_OWNER", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void cLOSE_TAB(IContext context, myfirstmodule.proxies.PrivateTotal _privateTotal, myfirstmodule.proxies.Tab _tab)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("PrivateTotal", _privateTotal == null ? null : _privateTotal.getMendixObject());
			params.put("Tab", _tab == null ? null : _tab.getMendixObject());
			Core.execute(context, "MyFirstModule.CLOSE_TAB", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createBeers(IContext context, myfirstmodule.proxies.Merchant _bar)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Bar", _bar == null ? null : _bar.getMendixObject());
			Core.execute(context, "MyFirstModule.CreateBeers", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void createRestaurantCourse(IContext context, myfirstmodule.proxies.Merchant _restaurant)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Restaurant", _restaurant == null ? null : _restaurant.getMendixObject());
			Core.execute(context, "MyFirstModule.CreateRestaurantCourse", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void dETECTED_QR(IContext context, myfirstmodule.proxies.QR _qR)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("QR", _qR == null ? null : _qR.getMendixObject());
			Core.execute(context, "MyFirstModule.DETECTED_QR", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.util.List<myfirstmodule.proxies.Product> gET_PRODUCTS_OF_TRANSATION(IContext context, myfirstmodule.proxies.Tab _tab)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Tab", _tab == null ? null : _tab.getMendixObject());
			java.util.List<IMendixObject> objs = Core.execute(context, "MyFirstModule.GET_PRODUCTS_OF_TRANSATION", params);
			java.util.List<myfirstmodule.proxies.Product> result = null;
			if (objs != null)
			{
				result = new java.util.ArrayList<myfirstmodule.proxies.Product>();
				for (IMendixObject obj : objs)
					result.add(myfirstmodule.proxies.Product.initialize(context, obj));
			}
			return result;
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.math.BigDecimal gET_SUM_TOTAL_OF_TAB(IContext context, myfirstmodule.proxies.Tab _tab)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Tab", _tab == null ? null : _tab.getMendixObject());
			return (java.math.BigDecimal)Core.execute(context, "MyFirstModule.GET_SUM_TOTAL_OF_TAB", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static myfirstmodule.proxies.User gET_USER(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.GET_USER", params);
			return result == null ? null : myfirstmodule.proxies.User.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void oPEN_NEW_TAB(IContext context, myfirstmodule.proxies.User _user)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("User", _user == null ? null : _user.getMendixObject());
			Core.execute(context, "MyFirstModule.OPEN_NEW_TAB", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static myfirstmodule.proxies.PrivateTotal pRIVATE_TOTAL(IContext context, myfirstmodule.proxies.Tab _tab)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Tab", _tab == null ? null : _tab.getMendixObject());
			IMendixObject result = (IMendixObject)Core.execute(context, "MyFirstModule.PRIVATE_TOTAL", params);
			return result == null ? null : myfirstmodule.proxies.PrivateTotal.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sAVE_CHANGES(IContext context, myfirstmodule.proxies.Product _product)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("Product", _product == null ? null : _product.getMendixObject());
			Core.execute(context, "MyFirstModule.SAVE_CHANGES", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static boolean sTARTUP_FLOW(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			return (java.lang.Boolean)Core.execute(context, "MyFirstModule.STARTUP_FLOW", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}