// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Tab
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tabMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Tab";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SUM("SUM"),
		STATUS("STATUS"),
		DUE_DATE("DUE_DATE"),
		Tab_User("MyFirstModule.Tab_User"),
		Tab_Merchant("MyFirstModule.Tab_Merchant");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Tab(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Tab"));
	}

	protected Tab(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tabMendixObject)
	{
		if (tabMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Tab", tabMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Tab");

		this.tabMendixObject = tabMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Tab.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Tab initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Tab.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Tab initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Tab(context, mendixObject);
	}

	public static myfirstmodule.proxies.Tab load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Tab.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Tab> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.Tab> result = new java.util.ArrayList<myfirstmodule.proxies.Tab>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.Tab" + xpathConstraint))
			result.add(myfirstmodule.proxies.Tab.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SUM
	 */
	public final java.math.BigDecimal getSUM()
	{
		return getSUM(getContext());
	}

	/**
	 * @param context
	 * @return value of SUM
	 */
	public final java.math.BigDecimal getSUM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.SUM.toString());
	}

	/**
	 * Set value of SUM
	 * @param sum
	 */
	public final void setSUM(java.math.BigDecimal sum)
	{
		setSUM(getContext(), sum);
	}

	/**
	 * Set value of SUM
	 * @param context
	 * @param sum
	 */
	public final void setSUM(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sum)
	{
		getMendixObject().setValue(context, MemberNames.SUM.toString(), sum);
	}

	/**
	 * Set value of STATUS
	 * @param status
	 */
	public final myfirstmodule.proxies.ENUM_TAB_STATUS getSTATUS()
	{
		return getSTATUS(getContext());
	}

	/**
	 * @param context
	 * @return value of STATUS
	 */
	public final myfirstmodule.proxies.ENUM_TAB_STATUS getSTATUS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.STATUS.toString());
		if (obj == null)
			return null;

		return myfirstmodule.proxies.ENUM_TAB_STATUS.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of STATUS
	 * @param status
	 */
	public final void setSTATUS(myfirstmodule.proxies.ENUM_TAB_STATUS status)
	{
		setSTATUS(getContext(), status);
	}

	/**
	 * Set value of STATUS
	 * @param context
	 * @param status
	 */
	public final void setSTATUS(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ENUM_TAB_STATUS status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.STATUS.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.STATUS.toString(), null);
	}

	/**
	 * @return value of DUE_DATE
	 */
	public final java.util.Date getDUE_DATE()
	{
		return getDUE_DATE(getContext());
	}

	/**
	 * @param context
	 * @return value of DUE_DATE
	 */
	public final java.util.Date getDUE_DATE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DUE_DATE.toString());
	}

	/**
	 * Set value of DUE_DATE
	 * @param due_date
	 */
	public final void setDUE_DATE(java.util.Date due_date)
	{
		setDUE_DATE(getContext(), due_date);
	}

	/**
	 * Set value of DUE_DATE
	 * @param context
	 * @param due_date
	 */
	public final void setDUE_DATE(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date due_date)
	{
		getMendixObject().setValue(context, MemberNames.DUE_DATE.toString(), due_date);
	}

	/**
	 * @return value of Tab_User
	 */
	public final myfirstmodule.proxies.User getTab_User() throws com.mendix.core.CoreException
	{
		return getTab_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Tab_User
	 */
	public final myfirstmodule.proxies.User getTab_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tab_User.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.User.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Tab_User
	 * @param tab_user
	 */
	public final void setTab_User(myfirstmodule.proxies.User tab_user)
	{
		setTab_User(getContext(), tab_user);
	}

	/**
	 * Set value of Tab_User
	 * @param context
	 * @param tab_user
	 */
	public final void setTab_User(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.User tab_user)
	{
		if (tab_user == null)
			getMendixObject().setValue(context, MemberNames.Tab_User.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Tab_User.toString(), tab_user.getMendixObject().getId());
	}

	/**
	 * @return value of Tab_Merchant
	 */
	public final myfirstmodule.proxies.Merchant getTab_Merchant() throws com.mendix.core.CoreException
	{
		return getTab_Merchant(getContext());
	}

	/**
	 * @param context
	 * @return value of Tab_Merchant
	 */
	public final myfirstmodule.proxies.Merchant getTab_Merchant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Merchant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Tab_Merchant.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Merchant.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Tab_Merchant
	 * @param tab_merchant
	 */
	public final void setTab_Merchant(myfirstmodule.proxies.Merchant tab_merchant)
	{
		setTab_Merchant(getContext(), tab_merchant);
	}

	/**
	 * Set value of Tab_Merchant
	 * @param context
	 * @param tab_merchant
	 */
	public final void setTab_Merchant(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Merchant tab_merchant)
	{
		if (tab_merchant == null)
			getMendixObject().setValue(context, MemberNames.Tab_Merchant.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Tab_Merchant.toString(), tab_merchant.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tabMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Tab that = (myfirstmodule.proxies.Tab) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Tab";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
